### ISSUE TITLE
Programmatically trigger open

### ISSUE THREAD

**Issue by zawilliams** [vsn4ik/bootstrap-submenu#11]
Hey @vsn4ik,

I'm having an issue programmatically triggering a dropdown using your plugin. I was trying to just use `$('#dropdownToBeClicked').click()` but can't get it to work. Is there a specific way to trigger this programmatically?

Thanks!

**Comment by alvarotrigo** [comment]
+1

**Comment by vsn4ik** [comment]
Work fine for me!
