### ISSUE TITLE
Submenu go to the start of the page when click

### ISSUE THREAD

**Issue by oroalej** [vsn4ik/bootstrap-submenu#12]
Hello, does anyone encounter this? the page go to the start of the page when i clicked it. this only happen when i view my website on mobile, and i am using the bootstrap menu bar responsive.

How can i make this stop?

**Comment by jhcarboni** [comment]
Actually yes, when I have to scroll the page to click in a menu item, this opens correctly the submenu items, but the page scrolls up to the top, so I need to scroll down to see the menu items again. Please can anyone help-me with this issue?

Thanks!

**Comment by ardouglass** [comment]
I posted a duplicate issue earlier today with a solution that worked for me: https://github.com/vsn4ik/bootstrap-submenu/issues/19.
