### ISSUE TITLE
First dropdown closes when trying to open submenu

### ISSUE THREAD

**Issue by timtime4** [vsn4ik/bootstrap-submenu#14]
I'm having an issue where I cannot view my submenu because the 1st dropdown closes on the click of one of the items in its list. I'm assuming this is because of the normal Bootstrap dropdown behavior. Is there something I need to do about this? For reference I'm using Bootstrap 3.3.5

**Comment by geggleto** [comment]
Hi timtime4,
I just had this problem as well, please make sure to wrap the initialize code in a dom-ready listener.

```
    <script type="application/javascript">
        $(document).ready(function () {
            $('.dropdown-submenu > a').submenupicker();
        });
    </script>
```

**Comment by vsn4ik** [comment]
Can you provide a jsfiddle for the problem?
