### ISSUE TITLE
On click, event.stopPropagation() failing

### ISSUE THREAD

**Issue by ardouglass** [vsn4ik/bootstrap-submenu#19]
I've never used event.stopPropagation(), but I assume it's supposed to work similarly to event.preventDefault() when clicking on anchors. I've only tested in the latest release of Chrome, but when I click a submenu item, the page scrolls to the top like I would expect if I clicked on ```<a href="#">```.

Adding event.preventDefault() fixed this for me, and the page no longer scrolls to the top when a submenu item is clicked.

I added it at this location: https://github.com/vsn4ik/bootstrap-submenu/blob/6d16184e074499cac9e72e1eba130aed3ddcae53/js/bootstrap-submenu.js#L71

**Comment by vsn4ik** [comment]
@ardouglass Can you provide a jsfiddle for the problem?
