### ISSUE TITLE
Support .navbar-right

### ISSUE THREAD

**Issue by CarstenF** [vsn4ik/bootstrap-submenu#22]
If a submenu is added to a menu of class `.navbar-right`, and the submenu items have a long/wide text, then the submenu does not grow beyond a width of 160px. This rule is needed to overcome the problem:

```
    .navbar-right .dropdown-submenu .dropdown-menu {
        right: auto;
    }
```

**Comment by vsn4ik** [comment]
@CarstenF Thanks for your report! Can you provide a jsfiddle for the problem?

**Comment by CarstenF** [comment]
@vsn4ik Many thanks for your efforts!
Fiddle showing the problem in Submenu v2.0.1 is at https://jsfiddle.net/hyko5xp7/

**Comment by vsn4ik** [comment]
https://jsfiddle.net/hyko5xp7/2/ (css from master).

![issue-22-1](https://cloud.githubusercontent.com/assets/3757319/11814635/e5f94c28-a358-11e5-85ed-02b2d10add0b.png)

@CarstenF This solution will suit you?

**Comment by CarstenF** [comment]
@vsn4ik This is clearly a good solution. It would be ideal though if we could choose whether submenus open left or right.

I see the logic and purpose in opening submenus in left-aligned menus to the right and submenus in right-aligned menus to the left. However, many people are more used to "open submenu to right" even in cases as the "Menu" in the fiddle, especially as this is also the natural reading direction for many languages.
