### ISSUE TITLE
Uncaught TypeError: Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by CodeBuzz** [vsn4ik/bootstrap-submenu#24]
Hi Folks,

I tried implementing bootstrap-submenu in my DoJo page but ended up getting this TyeError for this line of code in "bootstrap-submenu.js" Line No. 67
------------------------------------------------------------------
$.extend(SubmenuItem.prototype, Item.prototype, {
-----------------------------------------------------------------

Due to which I am unable to get the submenu-Dropdown in my page

Template of the page is as below

---------------------------------------------------
<ul class="dropdown-menu">
   			 <li class="dropdown-submenu">
				  <a tabindex="0">Another action</a>
				
				  <ul class="dropdown-menu">
				    <li class="dropdown-header">Dropdown header</li>
				    <li><a tabindex="0">Sub action</a></li>
				    <li class="disabled"><a tabindex="0">Another sub action</a></li>
				    <li><a tabindex="0">Something else here</a></li>
				  </ul>

----------------------------------------------------------
Can you please guide me resolve this issue?

Regards,
Amrish

**Comment by vsn4ik** [comment]
Load jQuery before load Bootstrap-submenu (js).
