### ISSUE TITLE
Submenu doesn't open

### ISSUE THREAD

**Issue by hulietta** [vsn4ik/bootstrap-submenu#25]
Hi!
My menu seems have some problem. When i click on the second submenus the first one disappear.
I've tried to add the script
 $('.dropdown-submenu > a').submenupicker();
 

But nothing happens!!

Here's the link of the site www.tecnopackspaimballaggi.com/prova

Thanks for your help

Giulia

**Comment by vsn4ik** [comment]
Use

```js
$('[data-toggle="dropdown"]').submenupicker();
```

**Comment by hulietta** [comment]
Thank you so much!!!! It works!!!!
