### ISSUE TITLE
Broken link on page: https://github.com/vsn4ik/bootstrap-submenu

### ISSUE THREAD

**Issue by rlbrenner** [vsn4ik/bootstrap-submenu#28]
The link for "Download the latest release" gives a 404. It is linking to 
https://github.com/vsn4ik/bootstrap-submenu/releases/download/v2.0.3/bootstrap-submenu-2.0.3-dist.zip

which apparently is incorrect.

**Comment by vsn4ik** [comment]
Thanks!
