### ISSUE TITLE
missing preventDefault() on click action

### ISSUE THREAD

**Issue by cicuz** [vsn4ik/bootstrap-submenu#3]
I believe there should be a call to preventDefault() bound to the click event: I'm adding a href attribute to my anchors for sameness' sake, and the browser gets sent around the page on click events on submenus.

What do you think?
Thanks for your work.

**Comment by vsn4ik** [comment]
Thanks for issue. I think adding `href` attribute for not passing `<a>` bad practice.

For fix this issue use before `$.fn.submenupicker` function this code:
```html
<script>
$('.dropdown-submenu > a').on('click.bs.dropdown', function(event) {
  event.preventDefault();
});
</script>
```
