### ISSUE TITLE
Rounded rectangle on Safari

### ISSUE THREAD

**Issue by kainjow** [vsn4ik/bootstrap-submenu#39]
On Safari (v9.1.1) when a submenu is clicked, it briefly shows the blue rounded rectangle. This doesn't show for normal Bootstrap menus.
![focusrect](https://cloud.githubusercontent.com/assets/271035/16506254/0f6a848c-3ed6-11e6-80b7-3fc5314f1ac9.png)

I was able to turn it off via:

```
.navbar .dropdown-submenu a {
    outline: none;
}
```

but I would suggest having this turned off in bootstrap-submenu's CSS directly.

**Comment by vsn4ik** [comment]
http://getbootstrap.com/javascript/#dropdowns. This is normal show for Bootstrap menus.

**Comment by kainjow** [comment]
What is that link supposed to show? I don't see the blue focus rect on anything from Bootstrap.

**Comment by zotalegre** [comment]
Not in navbar but yes, in pills--- oh boy...
