### ISSUE TITLE
Submenu ver 1.2.13 working, But ver 2.0.4 Not working

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [vsn4ik/bootstrap-submenu#44]
Hi,

1.Submenu version 1.2.13 is working fine.Click the drop down opening the Action menu, Action clicking opened display submenu sub action,... Refer this image

![image](https://cloud.githubusercontent.com/assets/9882142/24496251/4e63887c-1555-11e7-9e9d-ac604a5781ea.png)

Sample js fiddle link using ver 1.2.13 - https://jsfiddle.net/sattu/rvxuhgjv/1/

2.Latest ver 2.0.4,  Click the drop down opening the Action menu, Action clicking not opening next level menu. Plz refer the image 

![image](https://cloud.githubusercontent.com/assets/9882142/24496183/26c0a8fe-1555-11e7-8cca-b6574b851207.png)

Sample js fiddle link using ver 2.0.4 - https://jsfiddle.net/sattu/zpua4oww/15/

3. In git hub, https://github.com/vsn4ik/bootstrap-submenu/releases docs folder missing from ver 2.0.0 to ver 2.0.4. What is the reason? Up to ver 1.2.13 docs folder available.

Using ver 2.0.4 what I missed? Why submenu level 2 not working.

**Comment by vsn4ik** [comment]
You need add `data-submenu` or use `[data-toggle="dropdown"]` selector.

https://jsfiddle.net/zpua4oww/16/.

**Comment by DHANDAPANISATTANATHAN** [comment]
thanks vsn4ik. Now 2.0.4 working

**Comment by odahcam** [comment]
Why `data-submenu` is needed?
