### ISSUE TITLE
Order of initialisation is important

### ISSUE THREAD

**Issue by himdel** [vsn4ik/bootstrap-submenu#6]
Not sure whether to consider it a bug or not but it definitely bit me while trying to implement an angular wrapper... **nested submenus must be initialized in the outer > inner order**.

If you do it the other way around, individial submenus don't get closed when another is open on the same level, but only if the newly opened one is above the previously opened one.

If you decide it's not a bug, please mention it in the docs?
Thanks

**Comment by himdel** [comment]
For reference, this is what I ended up using, maybe somebody finds it useful.

    app.directive('dropdownSubmenu', function($timeout) {
    	return {
    		link: function(scope, elem, attrs) {
    			var lvl = ~~ attrs.level;
    			var fn = function() {
    				if (lvl > 0) {
    					lvl--;
    					$timeout(fn);
    					return;
    				}
    
    				$(elem).children('a').submenupicker();
    			};
    			fn();
    		},
    	};
    });

**Comment by vsn4ik** [comment]
Good case. I'll try to make it.

**Comment by pekur** [comment]
Hello vsn4ik, himdel,
could you please guide me how to use or where to place himdel's piece of code? Because what am I experiencing in my ASP.net app is that after opening page from submenu link, I cannot open the very same submenu again until another link from another part of menu is opened (probably the same issue as himdel has experienced).
Thanks

**Comment by himdel** [comment]
@pekur, you're unlikely to be able to use that code in an ASP.NET app, if it's indeed the same problem you just have to make sure you initialize the main menu first, then the submenus, then sub-submenus, and so on.

**Comment by abo3adel** [comment]
+1

**Comment by shaozi** [comment]
@himdel Can you give an example of the html on how to use your directive?
Thanks!

**Comment by himdel** [comment]
@shaozi The directive is not really meant to be used as is, it was mostly serving to demonstrate the problem.

After 2 years, I'm no longer sure it would quite work by itself and I no longer have the rest of the code.

That said, `<div dropdown-submenu level="1">` would be how you use it... And you can nest it by using different `level` values for sub-submenus.
