### ISSUE TITLE
LESS parsing error

### ISSUE THREAD

**Issue by mateuszjarzewski** [vsn4ik/bootstrap-submenu#9]
ParseError: Unrecognised input
in mixins.less on line 3, column 15:

2 // dashed: fix caret size for Mozilla Firefox
3 border-@{base}: @caret-width-base dashed;
4

**Comment by Gillingham** [comment]
I'm not seeing this issue with the current version, maybe @mateuszjarzewski is using an older version of lessc or other outdated less compiler?
